# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=30)),
                ('song_title', models.CharField(max_length=30)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('topic_name', models.CharField(max_length=30)),
                ('post_logo', models.CharField(max_length=30)),
                ('Question', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Threads'),
        ),
    ]
