# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170610_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_favorite',
        ),
    ]
