# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_comments_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='song_title',
        ),
    ]
