# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170610_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_body',
            field=models.CharField(default=django.utils.timezone.now, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
