# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.CharField(max_length=11),
        ),
    ]
