# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170611_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='date',
            field=models.CharField(default='nil', max_length=30),
        ),
        migrations.AlterField(
            model_name='threads',
            name='name',
            field=models.CharField(default='nil', max_length=30),
        ),
        migrations.AlterField(
            model_name='threads',
            name='post_logo',
            field=models.CharField(default='nil', max_length=30),
        ),
    ]
