# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='threads',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
