# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170618_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='date',
            field=models.DateTimeField(auto_now_add=True, max_length=10),
        ),
    ]
