# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='category1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
            preserve_default=False,
        ),
    ]
