# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_threads_category1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threads',
            old_name='category1',
            new_name='category',
        ),
    ]
